"""empty message

Revision ID: 9395b9d5b780
Revises: 
Create Date: 2022-04-05 18:57:47.044611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9395b9d5b780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ticket')),
    schema='TEST'
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['TEST.ticket.id'], name=op.f('fk__comment__ticket_id__ticket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__comment')),
    schema='TEST'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment', schema='TEST')
    op.drop_table('ticket', schema='TEST')
    # ### end Alembic commands ###
